#!/bin/bash

python code/main.py --experiment "embedding_loss" --optimized_letter "O" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "LION" --word "LION" --memo "with-new-font" > ./final_outputs/LION_full.txt
python code/main.py --experiment "conformal_0.5_dist_pixel_100_kernel201" --optimized_letter "O" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "LION" --word "LION" --memo "with-new-font" > ./final_outputs/LION_ori.txt
python code/main.py --experiment "off_losses" --optimized_letter "O" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "LION" --word "LION" --memo "with-new-font" > ./final_outputs/LION_no.txt
python code/main.py --experiment "embedding_loss" --optimized_letter "E" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "TENNIS" --word "TENNIS" --memo "with-new-font" > ./final_outputs/TENNIS_full.txt
python code/main.py --experiment "conformal_0.5_dist_pixel_100_kernel201" --optimized_letter "E" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "TENNIS" --word "TENNIS" --memo "with-new-font" > ./final_outputs/TENNIS_ori.txt
python code/main.py --experiment "off_losses" --optimized_letter "E" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "TENNIS" --word "TENNIS" --memo "with-new-font" > ./final_outputs/TENNIS_no.txt
python code/main.py --experiment "embedding_loss" --optimized_letter "N" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "ENGINEER" --word "ENGINEER" --memo "with-new-font" > ./final_outputs/ENGINEER_full.txt
python code/main.py --experiment "conformal_0.5_dist_pixel_100_kernel201" --optimized_letter "N" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "ENGINEER" --word "ENGINEER" --memo "with-new-font" > ./final_outputs/ENGINEER_ori.txt
python code/main.py --experiment "off_losses" --optimized_letter "N" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "ENGINEER" --word "ENGINEER" --memo "with-new-font" > ./final_outputs/ENGINEER_no.txt
python code/main.py --experiment "embedding_loss" --optimized_letter "M" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "MANGO" --word "MANGO" --memo "with-new-font" > ./final_outputs/MANGO_full.txt
python code/main.py --experiment "conformal_0.5_dist_pixel_100_kernel201" --optimized_letter "M" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "MANGO" --word "MANGO" --memo "with-new-font" > ./final_outputs/MANGO_ori.txt
python code/main.py --experiment "off_losses" --optimized_letter "M" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "MANGO" --word "MANGO" --memo "with-new-font" > ./final_outputs/MANGO_no.txt
python code/main.py --experiment "embedding_loss" --optimized_letter "R" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "SUNFLOWER" --word "SUNFLOWER" --memo "with-new-font" > ./final_outputs/SUNFLOWER_full.txt
python code/main.py --experiment "conformal_0.5_dist_pixel_100_kernel201" --optimized_letter "R" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "SUNFLOWER" --word "SUNFLOWER" --memo "with-new-font" > ./final_outputs/SUNFLOWER_ori.txt
python code/main.py --experiment "off_losses" --optimized_letter "R" --seed 0 --font "KaushanScript-Regular" --use_wandb 0 --wandb_user "none" --abstract "FALSE" --semantic_concept "SUNFLOWER" --word "SUNFLOWER" --memo "with-new-font" > ./final_outputs/SUNFLOWER_no.txt
